### ISSUE TITLE
Problems with the installation!

### ISSUE THREAD

**Issue by py-alpha-wolf** [imayhaveborkedit/discord-ext-speedups#1]
I'm using python 3.10.0a7, when I try to install discord-ext-speedups I always get this error here :
```ERROR: Could not find a version that satisfies the requirement discord-ext-speedups ERROR: No matching distribution found for discord-ext-speedups```.
How can I fix this?

**Comment by imayhaveborkedit** [comment]
This project was a cython and CI test.  It was not meant to actually be used.  It also did not produce any meaningful performance gains and will not be updated.
